# Basic
title: Red
subtitle: 海洋饼干
welcome_message: <a href="https://www.taptap.com/" target="_blank">TapTap发现好游戏</a>
description: Maybe i will write something here
creator: <a href="https://github.com/MonkeyKingSunWuKong">@LiKing</a>

url: "http://vno.onevcat.com"
permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
# cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Games, description: My Projects, url: 'https://www.taptap.com/'}
    - {title: Another Button, description: A button, url: 'http://baidu.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: MonkeyKingSunWuKong
    github: MonkeyKingSunWuKong
    twitter: MonkeyKingSunWuKong
    gplus: MonkeyKingSunWuKong
    mail: 1036211437@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
    